{% set name = "ioos_metrics" %}
{% set version = "0.1.0.dev0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ioos_metrics-{{ version }}.tar.gz
  sha256: 1686a2b327a00b69d0561ac4a1df6d54f1eadfdc34d2f645b629cae96f307244

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=42
    - setuptools-scm
    - pip
  run:
    - python >=3.10
    - bs4
    - ckanapi
    - fake-useragent
    - geopandas >=0.13.2
    - gliderpy
    - html5lib
    - joblib
    - lxml
    - pandas
    - pdfminer.six
    - pyarrow
    - requests

test:
  imports:
    - ioos_metrics
  # Cannot run pip-check when using beautifulsoup
  # commands:
  #  - pip check
  # requires:
  #   - pip

about:
  summary: Package to fetch various metrics for IOOS by the numbers
  home: https://github.com/ioos/ioos_metrics
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
