{% set python_min = "3.10" %}
{% set name = "ioos_metrics" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ioos_metrics-{{ version }}.tar.gz
  sha256: ac1ad740caee54e1be469666f4e4d3bf6a1b6a70d8ebd4589811cc5f6d332909

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - bs4
    - ckanapi
    - fake-useragent
    - geopandas >=0.13.2
    - gliderpy
    - html5lib
    - joblib
    - lxml
    - pandas
    - pdfminer.six
    - pyarrow
    - pyobis
    - requests

test:
  requires:
    - python {{ python_min }}
  imports:
    - ioos_metrics
  # Cannot run pip-check when using beautifulsoup
  # commands:
  #  - pip check
  # requires:
  #   - pip

outputs:
  - name: ioos_metrics
  - name: ioos-metrics
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - {{ pin_subpackage("ioos_metrics", max_pin="x.x.x") }}
        - python >={{ python_min }}
    test:
      requires:
        - python {{ python_min }}
      imports:
        - ioos_metrics

about:
  summary: Package to fetch various metrics for IOOS by the numbers
  home: https://github.com/ioos/ioos_metrics
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
